### ISSUE TITLE
Add basic CI to our repo

### ISSUE THREAD

**Issue by awenstrup** [olin-electric-motorsports/olin-electric-motorsports#3]
For now, just add a simple action to say hello world. As other infrastructure becomes mature, we can use this work as a starting point to build "real" continuous integration (CI).

**Comment by jack-greenberg** [comment]
Hm not sure if we are planning to use Github Issues yet or not, but this is totally fine for now :) We can use this as a place for discussion on features for CI if we want, or we can keep it on Confluence... maybe Confluence is better for now...

**Comment by jack-greenberg** [comment]
Closing this, thanks for adding in the basic support!
